substitutions:
  devicename: bedroom_ac
  label: Bedroom (AC)
  mount_room: bedroom
  mount_floor: "1"
  mount_height: "2.0" # in m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

<<: !include .template_base.yml


i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a

climate:
  - platform: daikin
    name: "AC ${label}"
    sensor: aht10_t
    state_topic: probrv2/${devicename}/${mount_floor}:${mount_room}:${mount_height}/climate/state

sensor:
  - platform: aht10
    temperature:
      name: "Temperature (AHT10) ${label}"
      state_topic: probrv2/${devicename}/${mount_floor}:${mount_room}:${mount_height}/aht10/temperature
      id: aht10_t
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3
        - calibrate_linear:
            - 0.0 -> 1.39
            - 10.0 -> 9.48
            - 20.0 -> 17.57
            - 30.0 -> 25.66
    humidity:
      name: "Humidity (AHT10) ${label}"
      state_topic: probrv2/${devicename}/${mount_floor}:${mount_room}:${mount_height}/aht10/humidity
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 3
        - calibrate_linear:
            - 30.0 -> 32.814
            - 40.0 -> 41.952
            - 50.0 -> 51.09
            - 60.0 -> 60.228
    update_interval: 20s

remote_transmitter:
  pin: D5
  carrier_duty_percent: 50%
