substitutions:
  devicename: childroom_ac
  label: Childroom (AC)
  mount_room: childroom
  mount_floor: "1"
  mount_height: "2.0" # in m

wifi:
  ssid: !secret wifi_ssid_ext
  password: !secret wifi_password

<<: !include .template_base.yml
# DO NOT INCLUDE AC TEMPLATE
# Using BME680
i2c:
  sda: D2
  scl: D1
  scan: True
  id: bus_a

bme680_bsec:
  address: 0x77

climate:
  - platform: daikin
    name: "AC ${label}"
    sensor: bme680_t
    receiver_id: ir_receiver

sensor:
  - platform: bme680_bsec
    temperature:
      id: bme680_t
      name: "Temperature (BME680) ${label}"
      state_topic: probrv2/${devicename}/${mount_floor}:${mount_room}:${mount_height}/bme680/temperature
    pressure:
      name: "Pressure (BME680) ${label}"
      state_topic: probrv2/${devicename}/${mount_floor}:${mount_room}:${mount_height}/bme680/pressure
    humidity:
      name: "Humidity (BME680) ${label}"
      state_topic: probrv2/${devicename}/${mount_floor}:${mount_room}:${mount_height}/bme680/humidity
    iaq:
      name: "IAQ (BME680) ${label}"
      state_topic: probrv2/${devicename}/${mount_floor}:${mount_room}:${mount_height}/bme680/iaq
    co2_equivalent:
      name: "CO2 Equivalent (BME680) ${label}"
      state_topic: probrv2/${devicename}/${mount_floor}:${mount_room}:${mount_height}/bme680/co2e
    breath_voc_equivalent:
      name: "VOC Equivalent (BME680) ${label}"
      state_topic: probrv2/${devicename}/${mount_floor}:${mount_room}:${mount_height}/bme680/voce

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "IAQ Accuracy (BME680) ${label}"

remote_transmitter:
  pin: D5
  carrier_duty_percent: 50%

remote_receiver:
  id: ir_receiver
  pin:
    number: D6
    inverted: True
    mode: INPUT_PULLUP
  # high 55% tolerance is recommended for some remote control units
  tolerance: 55%