substitutions:
  devicename: guestroom_ac
  label: Guestroom (AC)
  mount_room: guestroom
  mount_floor: "1"
  mount_height: "2.0" # in m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

<<: !include .template_ac_w_receiver.yml
