esphome:
  name: office
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "beta.otto.nay.comedian"

ota:
  password: "beta.otto.nay.comedian"

wifi:
  ssid: "arawa"
  password: "lauterschmutzigegeraete"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Office Fallback Hotspot"
    password: "WZCBARkrnphL"

captive_portal:

sensor:
  - platform: adc
    pin: A0
    name: "Office Light"
    update_interval: 5s
    unit_of_measurement: lx
    filters:
      - lambda: |-
          return (x / 10000.0) * -2000000.0 + 200;

remote_transmitter:
  pin: D0
  carrier_duty_percent: 50%

climate:
  - platform: daikin
    name: "Office AC"
